[env:esp32-s3-devkitc1-n16r8]
platform = espressif32
board = esp32-s3-devkitc1-n16r8
framework = arduino
upload_port = COM10
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps =
    olikraus/U8g2@^2.35.19
    nRF24/RF24@^1.4.9
    adafruit/Adafruit NeoPixel@^1.12.0
    Arduino-IRremote/IRremote@^4.4.0
    t-vk/ESP32 BLE Mouse@^0.3.1
build_flags =
    -Wl,-zmuldefs

