[platformio]
src_dir = ../HIZMOS_OLED_U8G2lib

[env:esp32-s3-devkitc1-n16r8]
platform = espressif32
board = esp32-s3-devkitc1-n16r8
framework = arduino
upload_port = COM10
monitor_speed = 115200

; Override flash size to match our 16MB N16R8 chip
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi

lib_deps =
    olikraus/U8g2@^2.35.19
    nRF24/RF24@^1.4.9
    adafruit/Adafruit NeoPixel@^1.12.0
    Arduino-IRremote/IRremote@^4.4.0
    t-vk/ESP32 BLE Mouse@^0.3.1

build_flags =
    -Wl,-zmuldefs
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=1
    -Wno-unused-variable

; UTF-8 encoding enforcement (prevents cp1252/charmap corruption)
monitor_filters = direct, colorize

extra_scripts =
    pre:patch.py
